### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by sincejune** [phodal/mole#10]
当前环境为Mac OS 10.11.6, node版本 6.5.0 npm版本3.10.7, npm使用taobao.org的源, 在使用了npm install指令后首先会出现许多指示内存可能溢出的指令,然后会有以下提示
<img width="749" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/19381524/18230858/7f12e22e-72da-11e6-8e30-5d48adf444a6.png">
使用了npm list之后会有后面的一些错误
<img width="699" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/19381524/18230856/7f0f3a7a-72da-11e6-80b0-f955794a3e28.png">
<img width="389" alt="pastedgraphic-3" src="https://cloud.githubusercontent.com/assets/19381524/18230855/7f0e3990-72da-11e6-88ce-46d10e1f42e6.png">
我尝试过安装eslint-config-airbnb-base包虽然能解决第一张图WARNING中的部分,但是上图警告中的第三行的错误一直无法解决, 就是当安装package.json指示的react的15.3.0版本时候,第三行的问题一直存在,npm list显示的树上也会有unmet peer dependecy的错误,当安装0.14.0的版本的时候,npm list显示的树上还是会有unmet peer dependecy的错误,之后再使用npm update react升级也没有改变, 虽然现在使用npm start可以跑起来 但是点击[新增文章]的[发送]按钮会出现以下错误.
<img width="1265" alt="pastedgraphic-4" src="https://cloud.githubusercontent.com/assets/19381524/18230857/7f118456-72da-11e6-9fd7-6fda68e4d525.png">

**Comment by phodal** [comment]
@SinceJune 看这情况，好像是没设置GitHub Token的缘故

**Comment by sincejune** [comment]
@phodal e... install的错误是因为没有设置Github Token么? 还是说下面的请求错误, 如果是下面的请求错误, 这个Github是在代码中的某处修改设置的么?

**Comment by phodal** [comment]
@SinceJune install错误可以不管~~。下面的请求错误是没设置GitHub Token
