### ISSUE TITLE
求大神带——新手如何让项目跑起来

### ISSUE THREAD

**Issue by zhuSilence** [phodal/mole#8]
> 高效的程序员和低效程序员间的十倍差距，至少有三倍是因为环境差异———phodal《Growth: 全栈增长工程师指南》

求教如何让新手把项目跑起来，稍微能缩短一下和高手之间的差距。。。

**Comment by sincejune** [comment]
@zhuSilence ReadMe中有写, package.json中还写了node和npm的版本要求

```
git clone git@github.com:phodal/mole.git
npm install
```
